export default function Home() {
  return (
    <main className="w-full">
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
      <h1>hello guys</h1>
    </main>
  );
}
